version: '3.8'

services:
  web:
    image: cheftory-homepage:latest
    container_name: cheftory-homepage
    restart: unless-stopped
    ports:
      - "3001:80"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    networks:
      - filient_net

networks:
  filient_net:
    external: true
